"""Migrações baseline

Revision ID: 0dfdb939f914
Revises: 
Create Date: 2024-03-28 12:33:06.135712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dfdb939f914'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essay',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('added_on', sa.DateTime(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('criteria_score_1', sa.Integer(), nullable=False),
    sa.Column('criteria_score_2', sa.Integer(), nullable=False),
    sa.Column('criteria_score_3', sa.Integer(), nullable=False),
    sa.Column('criteria_score_4', sa.Integer(), nullable=False),
    sa.Column('criteria_score_5', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('errors', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('essay')
    # ### end Alembic commands ###
