"""Remover não-nulo da coluna info da entidade Prompt

Revision ID: 93d42aee0c8b
Revises: 7dbf7a517ae2
Create Date: 2024-03-29 00:05:01.386517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d42aee0c8b'
down_revision: Union[str, None] = '7dbf7a517ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompt', 'info',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('prompt', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompt', 'date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('prompt', 'info',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
