"""Criando entidade Prompt e seu relacionamento com Essay

Revision ID: f6dd4b7b7c4d
Revises: 8e676dadc3c5
Create Date: 2024-03-28 13:27:48.435500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6dd4b7b7c4d'
down_revision: Union[str, None] = '8e676dadc3c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.Column('added_on', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('essay', sa.Column('prompt_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'essay', 'prompt', ['prompt_id'], ['id'])
    op.drop_column('essay', 'prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('essay', sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'essay', type_='foreignkey')
    op.drop_column('essay', 'prompt_id')
    op.drop_table('prompt')
    # ### end Alembic commands ###
